/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass *mrbc_init_class_symbol(struct VM *vm)
{
  static const mrbc_sym method_symbols[] = {
    MRBC_SYMID_all_symbols,
#if MRBC_USE_STRING
    MRBC_SYMID_id2name,
#endif
#if MRBC_USE_STRING
    MRBC_SYMID_inspect,
#endif
#if MRBC_USE_STRING
    MRBC_SYMID_to_s,
#endif
    MRBC_SYMID_to_sym,
  };
  static const mrbc_func_t method_functions[] = {
    c_symbol_all_symbols,
#if MRBC_USE_STRING
    c_symbol_to_s,
#endif
#if MRBC_USE_STRING
    c_symbol_inspect,
#endif
#if MRBC_USE_STRING
    c_symbol_to_s,
#endif
    c_ineffect,
  };

  return mrbc_define_builtin_class("Symbol", mrbc_class_object, method_symbols, method_functions, sizeof(method_symbols)/sizeof(mrbc_sym) );
}
