/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
static const mrbc_sym method_symbols_NilClass[] = {
#if MRBC_USE_STRING
  MRBC_SYMID_inspect,
#endif
  MRBC_SYMID_to_a,
#if MRBC_USE_FLOAT
  MRBC_SYMID_to_f,
#endif
  MRBC_SYMID_to_h,
  MRBC_SYMID_to_i,
#if MRBC_USE_STRING
  MRBC_SYMID_to_s,
#endif
};
static const mrbc_func_t method_functions_NilClass[] = {
#if MRBC_USE_STRING
  c_nil_inspect,
#endif
  c_nil_to_a,
#if MRBC_USE_FLOAT
  c_nil_to_f,
#endif
  c_nil_to_h,
  c_nil_to_i,
#if MRBC_USE_STRING
  c_nil_to_s,
#endif
};

struct RBuiltinClass mrbc_class_NilClass = {
  .sym_id = MRBC_SYM(NilClass),
  .num_builtin_method = sizeof(method_symbols_NilClass) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "NilClass",
#endif
  .super = mrbc_class_object,
  .method_link = 0,
  .method_symbols = method_symbols_NilClass,
  .method_functions = method_functions_NilClass,
};
