/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
static const mrbc_sym method_symbols_Range[] = {
  MRBC_SYMID_EQ_EQ_EQ,
  MRBC_SYMID_exclude_end_Q,
  MRBC_SYMID_first,
#if MRBC_USE_STRING
  MRBC_SYMID_inspect,
#endif
  MRBC_SYMID_last,
#if MRBC_USE_STRING
  MRBC_SYMID_to_s,
#endif
};
static const mrbc_func_t method_functions_Range[] = {
  c_range_equal3,
  c_range_exclude_end,
  c_range_first,
#if MRBC_USE_STRING
  c_range_inspect,
#endif
  c_range_last,
#if MRBC_USE_STRING
  c_range_inspect,
#endif
};

struct RBuiltinClass mrbc_class_Range = {
  .sym_id = MRBC_SYM(Range),
  .num_builtin_method = sizeof(method_symbols_Range) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "Range",
#endif
  .super = mrbc_class_object,
  .method_link = 0,
  .method_symbols = method_symbols_Range,
  .method_functions = method_functions_Range,
};
