/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
static const mrbc_sym method_symbols_Proc[] = {
  MRBC_SYMID_call,
#if MRBC_USE_STRING
  MRBC_SYMID_inspect,
#endif
  MRBC_SYMID_new,
#if MRBC_USE_STRING
  MRBC_SYMID_to_s,
#endif
};
static const mrbc_func_t method_functions_Proc[] = {
  c_proc_call,
#if MRBC_USE_STRING
  c_proc_to_s,
#endif
  c_proc_new,
#if MRBC_USE_STRING
  c_proc_to_s,
#endif
};

struct RBuiltinClass mrbc_class_Proc = {
  .sym_id = MRBC_SYM(Proc),
  .num_builtin_method = sizeof(method_symbols_Proc) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "Proc",
#endif
  .super = mrbc_class_object,
  .method_link = 0,
  .method_symbols = method_symbols_Proc,
  .method_functions = method_functions_Proc,
};
