/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
static const mrbc_sym method_symbols_Exception[] = {
  MRBC_SYM(message),
  MRBC_SYM(new),
};
static const mrbc_func_t method_functions_Exception[] = {
  c_exception_message,
  c_exception_new,
};

struct RBuiltinClass mrbc_class_Exception = {
  .sym_id = MRBC_SYM(Exception),
  .num_builtin_method = sizeof(method_symbols_Exception) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "Exception",
#endif
  .super = MRBC_CLASS(Object),
  .method_link = 0,
  .method_symbols = method_symbols_Exception,
  .method_functions = method_functions_Exception,
};
