/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass mrbc_class_NoMemoryError = {
  .sym_id = MRBC_SYM(NoMemoryError),
  .num_builtin_method = 0,
#if defined(MRBC_DEBUG)
  .names = "NoMemoryError",
#endif
  .super = MRBC_CLASS(Exception),
  .method_link = 0,
};
