/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass mrbc_class_NoMethodError = {
  .sym_id = MRBC_SYM(NoMethodError),
  .num_builtin_method = 0,
#if defined(MRBC_DEBUG)
  .names = "NoMethodError",
#endif
  .super = MRBC_CLASS(NameError),
  .method_link = 0,
};
