/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass *mrbc_init_class_nil(struct VM *vm)
{
  static const mrbc_sym method_symbols[] = {
#if MRBC_USE_STRING
    MRBC_SYMID_inspect,
#endif
    MRBC_SYMID_to_a,
#if MRBC_USE_FLOAT
    MRBC_SYMID_to_f,
#endif
    MRBC_SYMID_to_h,
    MRBC_SYMID_to_i,
#if MRBC_USE_STRING
    MRBC_SYMID_to_s,
#endif
  };
  static const mrbc_func_t method_functions[] = {
#if MRBC_USE_STRING
    c_nil_inspect,
#endif
    c_nil_to_a,
#if MRBC_USE_FLOAT
    c_nil_to_f,
#endif
    c_nil_to_h,
    c_nil_to_i,
#if MRBC_USE_STRING
    c_nil_to_s,
#endif
  };

  return mrbc_define_builtin_class("NilClass", mrbc_class_object, method_symbols, method_functions, sizeof(method_symbols)/sizeof(mrbc_sym) );
}
