/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass mrbc_class_ZeroDivisionError = {
  .sym_id = MRBC_SYM(ZeroDivisionError),
  .num_builtin_method = 0,
#if defined(MRBC_DEBUG)
  .names = "ZeroDivisionError",
#endif
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
};
