/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"

static const mrbc_sym method_symbols_FalseClass[] = {
#if MRBC_USE_STRING
  MRBC_SYM(inspect),
#endif
#if MRBC_USE_STRING
  MRBC_SYM(to_s),
#endif
};

static const mrbc_func_t method_functions_FalseClass[] = {
#if MRBC_USE_STRING
  c_false_to_s,
#endif
#if MRBC_USE_STRING
  c_false_to_s,
#endif
};

struct RBuiltinClass mrbc_class_FalseClass = {
  .sym_id = MRBC_SYM(FalseClass),
  .num_builtin_method = sizeof(method_symbols_FalseClass) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "FalseClass",
#endif
  .super = MRBC_CLASS(Object),
  .method_link = 0,
  .method_symbols = method_symbols_FalseClass,
  .method_functions = method_functions_FalseClass,
};
