/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass *mrbc_init_class_integer()
{
  static const mrbc_sym method_symbols[] = {
    MRBC_SYMID_MOD,
    MRBC_SYMID_AND,
    MRBC_SYMID_MUL_MUL,
    MRBC_SYMID_PLUS_AT,
    MRBC_SYMID_MINUS_AT,
    MRBC_SYMID_LT_LT,
    MRBC_SYMID_GT_GT,
    MRBC_SYMID_BL_BR,
    MRBC_SYMID_XOR,
    MRBC_SYMID_abs,
#if MRBC_USE_STRING
    MRBC_SYMID_chr,
#endif
#if MRBC_USE_STRING
    MRBC_SYMID_inspect,
#endif
#if MRBC_USE_FLOAT
    MRBC_SYMID_to_f,
#endif
    MRBC_SYMID_to_i,
#if MRBC_USE_STRING
    MRBC_SYMID_to_s,
#endif
    MRBC_SYMID_OR,
    MRBC_SYMID_NEG,
  };
  static const mrbc_func_t method_functions[] = {
    c_integer_mod,
    c_integer_and,
    c_integer_power,
    c_integer_positive,
    c_integer_negative,
    c_integer_lshift,
    c_integer_rshift,
    c_integer_bitref,
    c_integer_xor,
    c_integer_abs,
#if MRBC_USE_STRING
    c_integer_chr,
#endif
#if MRBC_USE_STRING
    c_integer_to_s,
#endif
#if MRBC_USE_FLOAT
    c_integer_to_f,
#endif
    c_ineffect,
#if MRBC_USE_STRING
    c_integer_to_s,
#endif
    c_integer_or,
    c_integer_not,
  };

  return mrbc_define_builtin_class(MRBC_SYM(Integer), mrbc_class_object, method_symbols, method_functions, sizeof(method_symbols)/sizeof(mrbc_sym) );
}
