/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
struct RClass *mrbc_init_class_fixnum(struct VM *vm)
{
  static const mrbc_sym method_symbols[] = {
    MRBC_SYMID_MOD,
    MRBC_SYMID_AND,
    MRBC_SYMID_MUL_MUL,
    MRBC_SYMID_PLUS_AT,
    MRBC_SYMID_MINUS_AT,
    MRBC_SYMID_LT_LT,
    MRBC_SYMID_GT_GT,
    MRBC_SYMID_BLL_BLR,
    MRBC_SYMID_HAT,
    MRBC_SYMID_abs,
#if MRBC_USE_STRING
    MRBC_SYMID_chr,
#endif
#if MRBC_USE_STRING
    MRBC_SYMID_inspect,
#endif
#if MRBC_USE_FLOAT
    MRBC_SYMID_to_f,
#endif
    MRBC_SYMID_to_i,
#if MRBC_USE_STRING
    MRBC_SYMID_to_s,
#endif
    MRBC_SYMID_OR,
    MRBC_SYMID_TILDE,
  };
  static const mrbc_func_t method_functions[] = {
    c_fixnum_mod,
    c_fixnum_and,
    c_fixnum_power,
    c_fixnum_positive,
    c_fixnum_negative,
    c_fixnum_lshift,
    c_fixnum_rshift,
    c_fixnum_bitref,
    c_fixnum_xor,
    c_fixnum_abs,
#if MRBC_USE_STRING
    c_fixnum_chr,
#endif
#if MRBC_USE_STRING
    c_fixnum_to_s,
#endif
#if MRBC_USE_FLOAT
    c_fixnum_to_f,
#endif
    c_ineffect,
#if MRBC_USE_STRING
    c_fixnum_to_s,
#endif
    c_fixnum_or,
    c_fixnum_not,
  };

  return mrbc_define_builtin_class("Fixnum", mrbc_class_object, method_symbols, method_functions, sizeof(method_symbols)/sizeof(mrbc_sym) );
}
