/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
static const mrbc_sym method_symbols_Object[] = {
  MRBC_SYMID_NOT,
  MRBC_SYMID_NOT_EQ,
  MRBC_SYMID_LT_EQ_GT,
  MRBC_SYMID_EQ_EQ_EQ,
  MRBC_SYMID_attr_accessor,
  MRBC_SYMID_attr_reader,
  MRBC_SYMID_block_given_Q,
  MRBC_SYMID_class,
  MRBC_SYMID_dup,
#if MRBC_USE_STRING
  MRBC_SYMID_inspect,
#endif
#if defined(MRBC_DEBUG)
  MRBC_SYMID_instance_methods,
#endif
#if defined(MRBC_DEBUG)
  MRBC_SYMID_instance_variables,
#endif
  MRBC_SYMID_is_a_Q,
  MRBC_SYMID_kind_of_Q,
#if defined(MRBC_DEBUG)
#if !defined(MRBC_ALLOC_LIBC)
  MRBC_SYMID_memory_statistics,
#endif
#endif
  MRBC_SYMID_new,
  MRBC_SYMID_nil_Q,
#if defined(MRBC_DEBUG)
  MRBC_SYMID_object_id,
#endif
  MRBC_SYMID_p,
  MRBC_SYMID_print,
#if MRBC_USE_STRING
  MRBC_SYMID_printf,
#endif
  MRBC_SYMID_puts,
  MRBC_SYMID_raise,
#if MRBC_USE_STRING
  MRBC_SYMID_sprintf,
#endif
#if MRBC_USE_STRING
  MRBC_SYMID_to_s,
#endif
};
static const mrbc_func_t method_functions_Object[] = {
  c_object_not,
  c_object_neq,
  c_object_compare,
  c_object_equal3,
  c_object_attr_accessor,
  c_object_attr_reader,
  c_object_block_given,
  c_object_class,
  c_object_dup,
#if MRBC_USE_STRING
  c_object_to_s,
#endif
#if defined(MRBC_DEBUG)
  c_object_instance_methods,
#endif
#if defined(MRBC_DEBUG)
  c_object_instance_variables,
#endif
  c_object_kind_of,
  c_object_kind_of,
#if defined(MRBC_DEBUG)
#if !defined(MRBC_ALLOC_LIBC)
  c_object_memory_statistics,
#endif
#endif
  c_object_new,
  c_object_nil,
#if defined(MRBC_DEBUG)
  c_object_object_id,
#endif
  c_object_p,
  c_object_print,
#if MRBC_USE_STRING
  c_object_printf,
#endif
  c_object_puts,
  c_object_raise,
#if MRBC_USE_STRING
  c_object_sprintf,
#endif
#if MRBC_USE_STRING
  c_object_to_s,
#endif
};

struct RBuiltinClass mrbc_class_Object = {
  .sym_id = MRBC_SYM(Object),
  .num_builtin_method = sizeof(method_symbols_Object) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "Object",
#endif
  .super = 0,
  .method_link = 0,
  .method_symbols = method_symbols_Object,
  .method_functions = method_functions_Object,
};
