/* Auto generated by make_method_table.rb */
#include "symbol_builtin.h"
static const mrbc_sym method_symbols_Float[] = {
#if MRBC_USE_MATH
  MRBC_SYMID_MUL_MUL,
#endif
  MRBC_SYMID_PLUS_AT,
  MRBC_SYMID_MINUS_AT,
  MRBC_SYMID_abs,
#if MRBC_USE_STRING
  MRBC_SYMID_inspect,
#endif
  MRBC_SYMID_to_f,
  MRBC_SYMID_to_i,
#if MRBC_USE_STRING
  MRBC_SYMID_to_s,
#endif
};
static const mrbc_func_t method_functions_Float[] = {
#if MRBC_USE_MATH
  c_float_power,
#endif
  c_float_positive,
  c_float_negative,
  c_float_abs,
#if MRBC_USE_STRING
  c_float_to_s,
#endif
  c_ineffect,
  c_float_to_i,
#if MRBC_USE_STRING
  c_float_to_s,
#endif
};

struct RBuiltinClass mrbc_class_Float = {
  .sym_id = MRBC_SYM(Float),
  .num_builtin_method = sizeof(method_symbols_Float) / sizeof(mrbc_sym),
#if defined(MRBC_DEBUG)
  .names = "Float",
#endif
  .super = mrbc_class_object,
  .method_link = 0,
  .method_symbols = method_symbols_Float,
  .method_functions = method_functions_Float,
};
